Homework14: Ekaterina Tsiunel
ETsiunel/homework-3-git pull request #13
Opened 2024-06-22 18:00 UTC by ETsiunel

homework_14_Files_Exceptions_Modules

2024-06-22 22:04 UTC, Stml89 requested changes

2024-06-22 22:04 UTC, Stml89 commented on hw_14/1.py
not really good module name

2024-06-22 22:04 UTC, Stml89 commented on hw_14/2.py
Good, but it does not take operator's priority into account:
1/ 2 + 2 * 2
2/ 2 ** 3 - 1

2024-06-23 09:55 UTC, ETsiunel commented on hw_14/1.py
it's not clear, why module name "1" is bad?

2024-06-23 09:57 UTC, ETsiunel commented on hw_14/2.py
ohh, i see((
I'll try to fix it

2024-06-26 13:52 UTC, ETsiunel commented on hw_14/2.py
fixed

2024-06-28 20:39 UTC, Stml89 commented on hw_14/1.py
if you were me or someone else, can you say what this module does? Why is it used without looking into the code?

2024-06-28 20:43 UTC, Stml89 requested changes
Pls, rename modules

2024-06-29 10:04 UTC, Stml89 approved these changes

2024-06-29 14:46 UTC, merged