Homework27: Ekaterina Tsiunel
ETsiunel/homework-3-git pull request #20
Opened 2024-08-16 00:56 UTC by ETsiunel

2024-08-16 01:09 UTC, ETsiunel commented
**(!) Note:** 
`/deleteUser` method is not working as well: received `{"error":"Order not found"}` in response. So it is always failed in my test. 
I hope sometime Dummy API will be fixed....maybe

2024-08-17 20:18 UTC, Stml89 requested changes

2024-08-17 20:18 UTC, Stml89 commented on hw_27/test_api.py
Everything in 1 module, this approach does not scale. Lots of code duplication. Need to separate test data, code and tests. But good usage of validation JSON schema

2024-08-20 21:48 UTC, ETsiunel commented on hw_27/test_api.py
reworked tests

2024-08-21 13:25 UTC, ETsiunel commented
@Stml89 changes are ready for review

2024-08-21 20:39 UTC, Stml89 approved these changes

2024-08-21 20:39 UTC, Stml89 commented on .gitignore
> +/Users/yekatsiarynatsyunel/Python/ItAcademyCourse/homeworks/hw_27/config.json
```suggestion
hw_27/config.json
```

2024-08-21 20:39 UTC, Stml89 commented on hw_27/api_model.py
> +    def _send_request(self, method, endpoint, data=None, params=None):
Really nice

2024-08-21 20:47 UTC, ETsiunel commented on .gitignore
> +/Users/yekatsiarynatsyunel/Python/ItAcademyCourse/homeworks/hw_27/config.json
fixed

2024-08-21 20:47 UTC, merged